modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "${neoforge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "${mod_github_link}/issues" #optional

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${mod_version}" #mandatory
    displayName = "${mod_name}" #mandatory
    authors = "${mod_authors}" #optional
    displayURL = "${mod_curseforge_link}" #optional
    description = '''${mod_description}''' #mandatory

[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId = "neoforge" #mandatory
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # 'required' requires the mod to exist, 'optional' does not
    # 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
    type="required" #mandatory
    # The version range of the dependency
    versionRange = "${neoforge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering = "NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange = "${neoforge_minecraft_version_range}"
    ordering = "NONE"
    side = "SERVER"
